### ISSUE TITLE
Specifying a project when querying for a workbook does not behave as expected

### ISSUE THREAD

**Issue by dotariel** [bryantbhowell/tableau_rest_api#11]
The "in project" filter when querying for workbooks only takes the project into account if there are more than one workbook with the same name. If only one workbook exists with the supplied name, then the project is not considered.

my_first_project:
- workbooks:
  - awesome_workbook

my_second_project:
- workbooks: 
  - shared_workbook

my_third_project:
- workbooks: 
  - shared_workbook

---

If I were to query for a workbook named "awesome_workbook" in "my_second_project", there should be no results. However, the workbook from `my_first_project` is returned.
If I were to query for `shared_workbook` in `my_first_project`, then it correctly fails to return a result, because now that `shared_workbook` exists more than once (across projects), it is taken into account in the filtering.

---
I'm not sure if this is by design, but it would seem more intuitive if the project filter was applied regardless of how many workbooks exist across projects. This would help prevent unintentionally deleting a workbook from a different project.

**Comment by bryantbhowell** [comment]
Hi Ariel,
I think you are right on the logic. I'm thinking of changing those methods to work like this. Let me know if you think there is any other case I am missing here:


```python
def query_datasource_luid_by_name_in_project(self, name, p_name_or_luid=False):
        self.start_log_block()
        datasources = self.query_datasources()
        datasources_with_name = datasources.xpath(u'//t:datasource[@name="{}"]'.format(name), namespaces=self.ns_map)
        if len(datasources_with_name) == 0:
            self.end_log_block()
            raise NoMatchFoundException(u"No datasource found with name {} in any project".format(name))
        elif p_name_or_luid is False:
            if len(datasources_with_name) == 1:
                self.end_log_block()
                return datasources_with_name[0].get("id")
            # If no project is declared, and
            else:
                raise MultipleMatchesFoundException(u'More than one datasource found by name {} without a project specified'.format(name))
        else:
            if self.is_luid(p_name_or_luid):
                ds_in_proj = datasources.xpath(u'//t:project[@id="{}"]/..'.format(p_name_or_luid), namespaces=self.ns_map)
            else:
                ds_in_proj = datasources.xpath(u'//t:project[@name="{}"]/..'.format(p_name_or_luid), namespaces=self.ns_map)
            if len(ds_in_proj) == 0:
                self.end_log_block()
                raise NoMatchFoundException(u"No datasource found with name {} in project {}".format(name, p_name_or_luid))
```

**Comment by dotariel** [comment]
Brian,

I think what you have there is what I was thinking as well. 

Thanks for all your efforts on this!

**Comment by dotariel** [comment]
@bryantbhowell Do you have an update on this?

**Comment by marotti** [comment]
@bryantbhowell Any update on this? Having the same issue.

**Comment by bryantbhowell** [comment]
Hi guys, I believe the updated code is available now over in the [tableau_tools](https://github.com/bryantbhowell/tableau_tools/) package. The tableau_rest_api library is now a sub-package in it and has all the updates I was working on prior to refactoring everything
